services:
    threedi.qaip.listener:
        class: threedi\qaip\event\main_listener
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@template'
            - '@language'
            - '%tables.attachments%'
            - '%core.root_path%'
        tags:
            - { name: event.listener }
